spring:
  cloud:
    gateway:
      server:
        webflux:
          routes: 
            - id: user-service
              uri: lb://USER-SERVICE
              predicates: 
                - Path=/api/users/**
                
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates: 
                - Path=/api/products/**
                
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates: 
                - Path=/api/orders/**
sever:
    port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
